Parte 1

package excepciones;

public class OperacionException extends RuntimeException{
    // contructor
    public OperacionException(String mensaje){
        super(mensaje);
    }
}


Parte 2

package aritmetica;

import excepciones.OperacionException;

public class Aritmetica {
    public static int division(int numerador, int denominador){
        if(denominador == 0){
            throw new OperacionException("Division entre cero");
        }
        return numerador / denominador;
    }
}


Parte 3

package test;

import static aritmetica.Aritmetica.division;
import excepciones.OperacionException;

public class TestExcepciones {

    public static void main(String[] args) {
        int resultado = 0;
        try {
            resultado = division(10, 0);
        } catch (OperacionException e) {
            System.out.println("Ocurrio un error de tipo OperacionException");
            System.out.println(e.getMessage());

        } catch (Exception e) {
            System.out.println("Ocurrio un Error");
            e.printStackTrace(System.out); // se conoce como la pila de excepciones
            System.out.println(e.getMessage());
        } finally {
            System.out.println("Se reviso la division entre cero");
        }
        System.out.println("La variable de resultado tiene como valor: " + resultado);
    }
}

